name: space_encyclopedia
description: General information about the Space.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  google_fonts: ^5.1.0

  flutter_carousel_slider: ^1.1.0
  lottie: ^2.6.0
  bubble: ^1.2.1
  easy_localization: ^3.0.2
  webview_flutter: ^4.2.3
  path_provider: ^2.1.0
  webview_flutter_android: ^3.9.3
  webview_flutter_wkwebview: ^3.7.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/lotties/
    - assets/languages/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
